import Vue from 'vue';
import Home from '@/components/Home.vue';
import DriverForm from '@/components/driver/DriverForm.vue';
import DriverTable from '@/components/driver/DriverTable.vue';
import DriverHomeView from '@/components/driver/DriverHomeView.vue';
import VehiculeForm from '@/components/vehicule/VehiculeForm.vue';
import VehiculeTable from '@/components/vehicule/VehiculeTable.vue';
import VehiculeHomeView from '@/components/vehicule/VehiculeHomeView.vue';
import VehiculeAssignmentTable from '@/components/vehicule-assignment/VehiculeAssignmentTable.vue';
import DriverDetail from '@/components/driver/DriverDetail.vue';
import VehiculeDetail from '@/components/vehicule/VehiculeDetail.vue';
import VehiculeAssignmentDetail from '@/components/vehicule-assignment/VehiculeAssignmentDetail.vue';
import VehiculeAssignmentFormDetail from '@/components/vehicule-assignment/VehiculeAssignmentFormDetail.vue';
import VehiculeAssignmentForm from '@/components/vehicule-assignment/VehiculeAssignmentForm.vue';
import Nav from '@/components/Nav.vue';
import Modal from '@/components/Modal.vue';

Vue.component('Home', Home);
Vue.component('DriverForm', DriverForm);
Vue.component('DriverTable', DriverTable);
Vue.component('DriverHomeView', DriverHomeView);
Vue.component('VehiculeForm', VehiculeForm);
Vue.component('VehiculeTable', VehiculeTable);
Vue.component('VehiculeHomeView', VehiculeHomeView);
Vue.component('VehiculeAssignmentTable', VehiculeAssignmentTable);
Vue.component('DriverDetail', DriverDetail);
Vue.component('VehiculeDetail', VehiculeDetail);
Vue.component('VehiculeAssignmentDetail', VehiculeAssignmentDetail);
Vue.component('VehiculeAssignmentFormDetail', VehiculeAssignmentFormDetail);
Vue.component('VehiculeAssignmentForm', VehiculeAssignmentForm);
Vue.component('Nav', Nav);
Vue.component('Modal', Modal);